# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  merge_to_master:
    runs-on: windows-latest
    steps:          
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
       run: echo "$GITHUB_CONTEXT"
      # Runs a set of commands using the runners shell
     - name: Get the GH variables
       run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Tag ref: $GITHUB_REF"
          
          
