# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  merge_to_master:
    runs-on: windows-latest
    steps:     
      - uses: actions/checkout@v2      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: 
          echo Add other actions to build
