# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  merge_to_master:
    runs-on: windows-latest
    steps:
      - env: 
         github_context: Brian
      - uses: actions/checkout@v2     
      
      - name: Show GH context
        run: echo github_context

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
