# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  merge_to_master:
    runs-on: windows-latest
    steps:        
     - name: Get Latest Tag
       uses: oprypin/find-latest-tag@v1.1.0
       with:
        repository: "api.github.com/repos/bpeacock001/ActionTest/git/refs/"

          
          
