# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  merge_to_master:
    runs-on: windows-latest
    steps:    
     - name: Get the GH variables     
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
     - name: GH tag url
       run: echo "$git_refs_url"
          
          
